package com.accenture.challengecompanies.infrastructure.persistence.mappings.company;

import com.accenture.challengecompanies.domain.models.Company;
import com.accenture.challengecompanies.infrastructure.persistence.mappings.address.AddressMapping;
import com.accenture.challengecompanies.infrastructure.persistence.mappings.supplier.SupplierMapping;
import jakarta.persistence.*;
import lombok.*;

import java.util.List;

@Entity
@Table(name = "companies")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(of = "id")
public class CompanyMapping {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(unique = true)
    private String cnpj;

    private String tradeName;

    @OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "address_id")
    private AddressMapping address;

    @ManyToMany
    @JoinTable(name = "company_supplier", joinColumns = @JoinColumn(name = "company_id"), inverseJoinColumns = @JoinColumn(name = "supplier_id"))
    private List<SupplierMapping> suppliers;

    public CompanyMapping(Company company) {
        this.cnpj = company.getCnpj();
        this.tradeName = company.getTradeName();
        this.address = new AddressMapping(company.getAddress());
    }

    public Company toModel() {
        return new Company(
                this.getId(),
                this.getCnpj(),
                this.getTradeName(),
                this.getAddress().toModel()
        );
    }
    // Constructors, getters, and setters are automatically generated by Lombok
}