package com.accenture.challengecompanies.infrastructure.persistence.mappings.address;

import com.accenture.challengecompanies.infrastructure.persistence.mappings.company.CompanyMapping;
import com.accenture.challengecompanies.infrastructure.persistence.mappings.supplier.SupplierMapping;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;

@Entity
@Table(name = "addresses")
@Getter
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(of = "id")
public class AddressMapping {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String street;
    private String number;
    private String complement;
    private String neighborhood;
    private String city;
    private String state;
    private String zipCode;
    private String country;

    @OneToOne(mappedBy = "address")
    private SupplierMapping supplier;

    @OneToOne(mappedBy = "address")
    private CompanyMapping company;

    // Constructors, getters, and setters are automatically generated by Lombok
}
